---
title:  "<font color=#005CE6> DemoCrawler </font>"
subtitle: <font color="green">Week 1</font>
author: 
    name: "Chih-Ping Chao"
    affiliation: <font color=#22dbea>木刻思股份有限公司</font>
    email: "course@agilearning.io, george@data-sci.info"
    website: "http://agilearning.io, https://github.com/whizzalan"
date: "December 26, 2015"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
options(width=120)
library(ggplot2)
library(plotly)
library(dplyr)
# rmarkdown::render("index.Rmd")
```

## YahooStock Demo

```{r YahooStock}
if(!file.exists("YahooStock.r")){
  download.file("https://raw.githubusercontent.com/datasci-info/RCrawler101-201512/gh-pages/week1/YahooStock.r", destfile = "YahooStock.r")
}
source("YahooStock.r")
dat <- yahooStockMajor.getData(2330)
# View(dat)
```

## TWSE Demo

- `encodeURIComponent=1&step=2&firstin=1&TYPEK=otc&code=`
- `encodeURIComponent=1&step=1&firstin=1&TYPEK=rotc&code=02`
- `encodeURIComponent=1&step=2&firstin=1&TYPEK=rotc&code=02`
- `encodeURIComponent=1&step=1&firstin=1&TYPEK=otc&code=02`

```{r TWSE}
if(!file.exists("TWSE.r")){
  download.file("https://github.com/datasci-info/RCrawler101-201512/blob/gh-pages/week1/TWSE.r", destfile = "TWSE.r")
}
source("TWSE.r")
dat <- TWSE.postData()
# View(dat)
```



<iframe width=750 height=500 frameborder="0" seamless="seamless" scrolling="no" src="https://plot.ly/~whizzalan/8.embed"> </iframe>